=== What is JDBC template?

*Jdbc Template* is a class located in `org.springframework.jdbc.core` package. Goal of this class is to simplify use of JDBC by providing implementation of JDBC workflow, leaving application to provide SQL statements and results extractions.

Jdbc Template executes SQL queries or updates, initiates iteration over ResultSet, ResultSet mapping, also it catches exceptions and translates them into generic exceptions.


Code that interacts with Jdbc Template needs to provide implementation of callback interfaces which allows specific steps of JDBC workflow customization: ::
- PreparedStatementCreator
- ResultSetExtractor
- PreparedStatementSetter
- RowMapper

=== What is a callback? What are the three JdbcTemplate callback interfaces that can be used with queries? What is each used for?

A callback is a code or reference to the code that can be passed as an argument to the method. This method will execute passed callback during execution.

On Java level callback can be: ::
- Class that implements interface
- Anonymous class
- Lambda expression – JDK 8
- Reference Method – JDK 8
